# Exercise 16 - Pandemic taxis

In this exercise, I want you to create a data frame from two different CSV files containing New York taxi data: one from July 2019 (before the pandemic) and a second from July 2020 (near the height of the pandemic, at least in New York). The data frame should contain three columns from the files: ```passenger_count```, ```total_amount```, and ```payment_type```. It should also include a fifth column, ```year```, which should be set to 2019 or 2020, depending on the file from which the data was loaded.

* Load data from july 2019:

In [47]:
# NOTE: files nyc_taxy_2019-07.csv and nyc_taxy_2020-7.csv are not included due to its size. Get them from book's repository.

import pandas as pd

taxi_rides_2019 = pd.read_csv(
    "./nyc_taxi_2019-07.csv", # data from july 2019
    header=0,
    usecols=["passenger_count", "total_amount", "payment_type"],
)

taxi_rides_2019["year"] = 2019 # define column year

taxi_rides_2019.head(10)

   passenger_count  payment_type  total_amount  year
0              1.0           1.0          4.94  2019
1              1.0           2.0         20.30  2019
2              1.0           1.0         70.67  2019
3              1.0           1.0         66.36  2019
4              0.0           1.0         15.30  2019
5              0.0           1.0         16.55  2019
6              1.0           1.0         20.15  2019
7              1.0           2.0         16.30  2019
8              1.0           1.0         35.76  2019
9              1.0           2.0         16.30  2019

* Load data from july 2020:

In [48]:
taxi_rides_2020 = pd.read_csv(
    "./nyc_taxi_2020-07.csv", # data from july 2020
    header=0,
    usecols=["passenger_count", "total_amount", "payment_type"],
)

taxi_rides_2020["year"] = 2020 # define column year

taxi_rides_2020.head(10)

   passenger_count  payment_type  total_amount  year
0              1.0           2.0          9.30  2020
1              1.0           1.0         27.80  2020
2              1.0           2.0         22.30  2020
3              1.0           1.0         14.16  2020
4              1.0           2.0          7.80  2020
5              1.0           1.0         33.80  2020
6              1.0           1.0         26.39  2020
7              1.0           2.0          8.80  2020
8              1.0           1.0         10.12  2020
9              1.0           1.0         66.36  2020

* concat both Dataframes:

In [49]:
taxi_rides = pd.concat([taxi_rides_2019, taxi_rides_2020])

taxi_rides.head(10)

   passenger_count  payment_type  total_amount  year
0              1.0           1.0          4.94  2019
1              1.0           2.0         20.30  2019
2              1.0           1.0         70.67  2019
3              1.0           1.0         66.36  2019
4              0.0           1.0         15.30  2019
5              0.0           1.0         16.55  2019
6              1.0           1.0         20.15  2019
7              1.0           2.0         16.30  2019
8              1.0           1.0         35.76  2019
9              1.0           2.0         16.30  2019

With that data in hand, I want you to answer a few questions:

* How many rides were taken in 2019 and 2020, and what is the difference between these two figures?

In [50]:
rides_2019 = taxi_rides.loc[taxi_rides["year"] == 2019, "passenger_count"].count()
rides_2020 = taxi_rides.loc[taxi_rides["year"] == 2020, "passenger_count"].count()

print(f"Rides in 2019: {rides_2019:,.0f}\nRides in 2020: {rides_2020:,.0f}\nDifference: {rides_2019 - rides_2020:,.0f}")

Rides in 2019: 6,276,460
Rides in 2020: 737,565
Difference: 5,538,895

* How much money (in total) was collected in 2019 and 2020, and what was the difference between these two figures?

In [51]:
money_2019 = taxi_rides.loc[taxi_rides.year == 2019, "total_amount"].sum()
money_2020 = taxi_rides.loc[taxi_rides.year == 2020, "total_amount"].sum()

print(f"Money 2019: ${money_2019:,.2f}\nMoney 2020: ${money_2020:,.2f}\nDifference: ${money_2019 - money_2020:,.2f}")

Money 2019: $123,761,823.33
Money 2020: $14,912,844.09
Difference: $108,848,979.24

* Did the proportion of trips with more than one passenger change dramatically?

In [52]:
rides_multiple_passengers_2019 = taxi_rides.query("(passenger_count > 1) & (year == 2019)").shape[0]
rides_multiple_passengers_2019_prop = (rides_multiple_passengers_2019 / rides_2019)

rides_multiple_passengers_2020 = taxi_rides.query("(passenger_count > 1) & (year == 2020)").shape[0]
rides_multiple_passengers_2020_prop = (rides_multiple_passengers_2020 / rides_2020)

print(f"Proportion of more of one passenger rides in 2019: {rides_multiple_passengers_2019_prop:.2f}\n"
      f"Proportion of more of one passenger rides in 2020: {rides_multiple_passengers_2020_prop:.2f}"
      )

Proportion of more of one passenger rides in 2019: 0.28
Proportion of more of one passenger rides in 2020: 0.21

**Answer:** the proportion of rides with more than one passenger in 2020 decreased in almost a third in comparison with 2019.

* Did people use cash (i.e., ```payment_type``` of 2) less in 2020 than in 2019?

In [53]:
CASH = 2 # cash is payment type number 2
paid_in_cash_2019 = taxi_rides.loc[(taxi_rides.year == 2019) & (taxi_rides["payment_type"] == CASH)].shape[0]
paid_in_cash_2019_prop = paid_in_cash_2019 / rides_2019

paid_in_cash_2020 = taxi_rides.query("(year == 2020) & (payment_type == @CASH)").shape[0]
paid_in_cash_2020_prop = paid_in_cash_2020 / rides_2020

print(f"Proportion of rides paid in cash in 2019: {paid_in_cash_2019_prop:.2f}\n"
      f"Proportion of rides paid in cash in 2020: {paid_in_cash_2020_prop:.2f}\n")

Proportion of rides paid in cash in 2019: 0.29
Proportion of rides paid in cash in 2020: 0.32

**Answer:** the use of cash in 2020 is a little higher than in 2019.

## Beyond the exercise

* Use the ```corr``` method on ```df``` to find the correlations among the columns. How would you interpret these results?

In [54]:
correlations = taxi_rides.corr()

correlations

                 passenger_count  payment_type  total_amount      year
passenger_count         1.000000      0.016410      0.014943 -0.049558
payment_type            0.016410      1.000000     -0.138561  0.029277
total_amount            0.014943     -0.138561      1.000000 -0.019706
year                   -0.049558      0.029277     -0.019706  1.000000

**Answer:** From above it can be seen that the columns are not correlated (values near ```0```).

* Show, with a single command, the difference in descriptive statistics for ```total_amount``` between 2019 and 2020. Round values to use no more than two digits after the decimal point.

In [55]:
taxi_rides.loc[taxi_rides["year"] == 2019, "total_amount"].describe().round(2) - \
taxi_rides.loc[taxi_rides["year"] == 2020, "total_amount"].describe().round(2)

count    5510007.00
mean           0.98
std            0.75
min          -53.20
25%            0.50
50%            0.60
75%            0.75
max         4672.45
Name: total_amount, dtype: float64

* If we assume that zero-passenger trips are for delivering packages, how were those affected during the pandemic? Show the proportion of such trips in 2019 versus 2020.

In [56]:
packages_2019 = taxi_rides.loc[(taxi_rides["year"] == 2019) & (taxi_rides["passenger_count"] == 0), "passenger_count"].count()
packages_2019_prop = packages_2019 / rides_2019

packages_2020 = taxi_rides.loc[(taxi_rides["year"] == 2020) & (taxi_rides["passenger_count"] == 0), "passenger_count"].count()
packages_2020_prop = packages_2020 / rides_2020

print(f"Proportion of packages delivered in 2019: {packages_2019_prop:.2f}\n"
      f"Proportion of packages delivered in 2020: {packages_2020_prop:.2f}"
      )

Proportion of packages delivered in 2019: 0.02
Proportion of packages delivered in 2020: 0.03

**Answer:** the proportion of packages delivered in 2020 is more or less the same as in 2019.