# Exercise 17 - Setting column types

Once again, I want you to create a data frame based on New York taxi data from January 2020. This time, however, I want to ensure that the data is in the most appropriate and compact form it can be and will use as little memory as possible when being loaded. So, I want you to do the following:

*  Specify the dtype for each column as you read it in.

In [2]:
import pandas as pd
import numpy as np
from numpy.ma.core import shape

taxi_rides = pd.read_csv(
    "./nyc_taxi_2020-01.csv",
    header=0,
    usecols=["passenger_count", "total_amount", "payment_type"],
)

taxi_rides.head(10)

   passenger_count  payment_type  total_amount
0              1.0           1.0         11.27
1              1.0           1.0         12.30
2              1.0           1.0         10.80
3              1.0           1.0          8.16
4              1.0           2.0          4.80
5              1.0           2.0          3.80
6              1.0           1.0          3.81
7              1.0           1.0          2.81
8              4.0           1.0          6.30
9              2.0           1.0         14.15

*  Identify rows containing ```NaN``` values. Which columns are ```NaN```, and why?

In [3]:
nan_rows = taxi_rides.loc[
    (taxi_rides["passenger_count"].isna()) | \
    (taxi_rides["payment_type"].isna()) | \
    (taxi_rides["total_amount"].isna())
].shape[0]

print(f"Number of rows with NaN values: {nan_rows}\n"
      f"Percentage of rows with NaN values: {(nan_rows / taxi_rides.shape[0]) * 100:.2f}%"
      )

Number of rows with NaN values: 65441
Percentage of rows with NaN values: 1.02%

* Remove any rows containing any ```NaN``` values.

In [4]:
taxi_rides = taxi_rides.copy().dropna()

nan_rows = taxi_rides.loc[
    (taxi_rides["passenger_count"].isna()) | \
    (taxi_rides["payment_type"].isna()) | \
    (taxi_rides["total_amount"].isna())
    ].shape[0]

nan_rows

0

*  Set the ```dtype``` for each column to the smallest, most appropriate value.

In [5]:
taxi_rides["passenger_count"] = taxi_rides["passenger_count"].astype(np.int8)
taxi_rides["payment_type"] = taxi_rides["payment_type"].astype(np.int8)
taxi_rides["total_amount"] = taxi_rides["total_amount"].astype(np.float32)

taxi_rides.head(10)

   passenger_count  payment_type  total_amount
0                1             1         11.27
1                1             1         12.30
2                1             1         10.80
3                1             1          8.16
4                1             2          4.80
5                1             2          3.80
6                1             1          3.81
7                1             1          2.81
8                4             1          6.30
9                2             1         14.15

## Beyond the exercise

* Create a data frame from four other columns (```VendorID```, ```trip_distance```, ```tip_amount```, and ```total_amount```), specifying the ```dtype``` for each. What types are most appropriate? Can you use them directly, or must you first clean the data?

In [7]:
taxi_rides_2 = pd.read_csv(
    "./nyc_taxi_2020-01.csv",
    header=0,
    usecols=["VendorID", "trip_distance", "tip_amount", "total_amount"],
)

taxi_rides_2.head(10)

   VendorID  trip_distance  tip_amount  total_amount
0       1.0           1.20        1.47         11.27
1       1.0           1.20        1.50         12.30
2       1.0           0.60        1.00         10.80
3       1.0           0.80        1.36          8.16
4       2.0           0.00        0.00          4.80
5       2.0           0.03        0.00          3.80
6       2.0           0.00        0.01          3.81
7       2.0           0.00        0.00          2.81
8       2.0           0.00        0.00          6.30
9       1.0           0.70        2.35         14.15

In [14]:
nan_rows = taxi_rides_2.loc[
    taxi_rides_2["VendorID"].isna() | \
    taxi_rides_2["trip_distance"].isna() |
    taxi_rides_2["tip_amount"].isna() | \
    taxi_rides_2["total_amount"].isna()
].shape[0]

print(f"Number of rows with NaN values: {nan_rows:,.0f}\n"
      f"Percentage of of rows with NaN values: {(nan_rows / taxi_rides_2.shape[0]) * 100:.2f}%")

Number of rows with NaN values: 65,441
Percentage of of rows with NaN values: 1.02%

There are ```NaN``` values in the dataset, why must clean the data before assigning a ```dtype``` to each column:

In [18]:
taxi_rides_2_clean = taxi_rides_2.copy().dropna()

nan_rows = taxi_rides_2_clean.loc[
    taxi_rides_2_clean["VendorID"].isna() | \
    taxi_rides_2_clean["trip_distance"].isna() |
    taxi_rides_2_clean["tip_amount"].isna() | \
    taxi_rides_2_clean["total_amount"].isna()
].shape[0]

print(f"Number of rows with NaN values: {nan_rows:,.0f}\n"
      f"Percentage of of rows with NaN values: {(nan_rows / taxi_rides_2_clean.shape[0]) * 100:.2f}%")

Number of rows with NaN values: 0
Percentage of of rows with NaN values: 0.00%

```VendorID``` must be ```np.int8```, ```trip_distance```, ```tip_amount```, and ```total_amount``` can be ```np.float32```

In [19]:
taxi_rides_2_clean["VendorID"] = taxi_rides_2_clean["VendorID"].astype(np.int8)
taxi_rides_2_clean["trip_distance"] = taxi_rides_2_clean["trip_distance"].astype(np.float32)
taxi_rides_2_clean["tip_amount"] = taxi_rides_2_clean["tip_amount"].astype(np.float32)
taxi_rides_2_clean["total_amount"] = taxi_rides_2_clean["total_amount"].astype(np.float32)

taxi_rides_2_clean.head(10)

   VendorID  trip_distance  tip_amount  total_amount
0         1       1.200195    1.469727     11.273438
1         1       1.200195    1.500000     12.296875
2         1       0.600098    1.000000     10.796875
3         1       0.799805    1.360352      8.156250
4         2       0.000000    0.000000      4.800781
5         2       0.029999    0.000000      3.800781
6         2       0.000000    0.010002      3.810547
7         2       0.000000    0.000000      2.810547
8         2       0.000000    0.000000      6.300781
9         1       0.700195    2.349609     14.148438

* Instead of removing ```NaN``` values from the ```VendorID``` column, set it to a new value: **3**. How does that affect your specifications and cleaning of the data?

In [20]:
taxi_rides_2.loc[taxi_rides_2["VendorID"].isna(), "VendorID"] = 3

nan_rows = taxi_rides_2.loc[
    taxi_rides_2["VendorID"].isna() | \
    taxi_rides_2["trip_distance"].isna() |
    taxi_rides_2["tip_amount"].isna() | \
    taxi_rides_2["total_amount"].isna()
].shape[0]

print(f"Number of rows with NaN values: {nan_rows:,.0f}\n"
      f"Percentage of of rows with NaN values: {(nan_rows / taxi_rides_2.shape[0]) * 100:.2f}%")

Number of rows with NaN values: 0
Percentage of of rows with NaN values: 0.00%

Making this change there are not more ```NaN``` values in the dataset, and is not necessary to clean the data.

* We’ll talk more about this in Chapter 11, but the ```memory_usage``` method allows you to see how much memory is being used by each column in a data frame. It returns a series of integers in which the index lists the columns, and the values represent the memory used by each column. Compare the memory used by the data frame with ```float32``` (which you’ve already used) and when you use ```float64``` instead for the final three columns.

In [21]:
taxi_rides_2_clean.memory_usage() # dtypes: int6, float32, float32, float32

Index                 132
VendorID          6339567
trip_distance    25358268
tip_amount       25358268
total_amount     25358268
dtype: int64

In [22]:
# change columns with dtype float32 to float64

taxi_rides_2_clean["trip_distance"] = taxi_rides_2_clean["trip_distance"].astype(np.float64)
taxi_rides_2_clean["tip_amount"] = taxi_rides_2_clean["tip_amount"].astype(np.float64)
taxi_rides_2_clean["total_amount"] = taxi_rides_2_clean["total_amount"].astype(np.float64)

taxi_rides_2_clean.memory_usage()

Index                 132
VendorID          6339567
trip_distance    50716536
tip_amount       50716536
total_amount     50716536
dtype: int64