# Exercise 26 - Celebrity deaths

For this exercise, we’ll look at a (slightly morbid) data set: a list of celebrities who died in 2016 and whose passing was recorded in Wikipedia, including the date of death, a short biography, and the cause of death. The problem is that this data set is messy, with some missing data and some erroneous data that will prevent us from working with it easily. The goal of this exercise is to find the average age of celebrities who died February–July 2016. Getting there will take several steps:

1. Create a data frame from the file ```celebrity_deaths_2016.csv```. For this exercise, we’ll use only two columns: ```ageofdeath``` and ```age```.

In [29]:
import pandas as pd

dead_celebrities = pd.read_csv(
    "celebrity_deaths_2016.csv",
    header=0,
    usecols=["dateofdeath", "age"]
)

dead_celebrities.head(10)

  dateofdeath age
0  2016-01-01  71
1  2016-01-01  74
2  2016-01-01  79
3  2016-01-01  45
4  2016-01-01  83
5  2016-01-01  71
6  2016-01-01  92
7  2016-01-01  99
8  2016-01-01  45
9  2016-01-01  58

2. Create a new ```month``` column containing the month from the ```dateofdeath``` column.

In [30]:
dead_celebrities["month"] = dead_celebrities["dateofdeath"].str.slice(5, 7)
dead_celebrities.head(10)

  dateofdeath age month
0  2016-01-01  71    01
1  2016-01-01  74    01
2  2016-01-01  79    01
3  2016-01-01  45    01
4  2016-01-01  83    01
5  2016-01-01  71    01
6  2016-01-01  92    01
7  2016-01-01  99    01
8  2016-01-01  45    01
9  2016-01-01  58    01

3. Make the ```month``` column the index of the data frame.

In [31]:
dead_celebrities = dead_celebrities.set_index("month")
dead_celebrities.head(10)

      dateofdeath age
month
01     2016-01-01  71
01     2016-01-01  74
01     2016-01-01  79
01     2016-01-01  45
01     2016-01-01  83
01     2016-01-01  71
01     2016-01-01  92
01     2016-01-01  99
01     2016-01-01  45
01     2016-01-01  58

4. Sort the data frame by the index.

In [32]:
dead_celebrities = dead_celebrities.sort_index()
dead_celebrities.head(10)

      dateofdeath age
month
01     2016-01-01  71
01     2016-01-21  47
01     2016-01-21  87
01     2016-01-21  90
01     2016-01-21  73
01     2016-01-21  37
01     2016-01-21  59
01     2016-01-21  75
01     2016-01-21  97
01     2016-01-21  78

5. Clean all nonintegers from the age column.

In [33]:
dead_celebrities = dead_celebrities.loc[dead_celebrities["age"].str.isdigit()]
dead_celebrities.head(10)

      dateofdeath age
month
01     2016-01-01  71
01     2016-01-21  47
01     2016-01-21  87
01     2016-01-21  90
01     2016-01-21  73
01     2016-01-21  37
01     2016-01-21  59
01     2016-01-21  75
01     2016-01-21  97
01     2016-01-21  78

6. Turn the ```age``` column into an integer value.

In [34]:
import numpy as np

dead_celebrities["age"] = dead_celebrities["age"].astype(np.int64)
dead_celebrities.head(10)

      dateofdeath  age
month
01     2016-01-01   71
01     2016-01-21   47
01     2016-01-21   87
01     2016-01-21   90
01     2016-01-21   73
01     2016-01-21   37
01     2016-01-21   59
01     2016-01-21   75
01     2016-01-21   97
01     2016-01-21   78

7. Find the average age of celebrities who died during that period (Feb-Jul 2016).

In [35]:
mean_age = dead_celebrities.loc["02":"07", "age"].mean()

print(f"Mean age of dead celebrities between Feb and Jul of 2016: {mean_age:.1f} years old.")

Mean age of dead celebrities between Feb and Jul of 2016: 77.2 years old.

## Beyond the exercise

*  Add a new column, ```day```, from the day of the month in which the celebrity died. Then create a multi-index (from ```month``` and ```day```). What was the average age of death from Feb. 15 through July 15?

In [36]:
# create day column
dead_celebrities["day"] = dead_celebrities["dateofdeath"].str.slice(8, 10)

In [37]:
# create multi-index
dead_celebrities = dead_celebrities.reset_index()
dead_celebrities = dead_celebrities.set_index(["month", "day"])
dead_celebrities = dead_celebrities.sort_index()
dead_celebrities.head(10)

          dateofdeath  age
month day
01    01   2016-01-01   71
      01   2016-01-01   93
      01   2016-01-01   74
      01   2016-01-01   79
      01   2016-01-01   45
      01   2016-01-01   83
      01   2016-01-01   71
      01   2016-01-01   92
      01   2016-01-01   99
      01   2016-01-01   45

In [39]:
mean_age = dead_celebrities.loc[("02", "15"):("07", "15"), "age"].mean()

print(f"Mean age of celebrity deaths between Feb 15 and Jul 15 of 2016: {mean_age:.1f} years old.")

Mean age of celebrities deaths between Feb 15 and Jul 15 of 2016: 77.1 years old.

* The CSV file contains another column, ```causeofdeath```. Load it into a dataframe, and find the five most common causes of death. Now replace any ```NaN``` values in that column with the string ```unknown```, and again find the five most common causes of death.

In [40]:
df = pd.read_csv(
    "./celebrity_deaths_2016.csv",
    header=0,
    usecols=["dateofdeath", "age", "causeofdeath"]
)

# get the five most common causes of death
df["causeofdeath"].value_counts().head(5)

causeofdeath
cancer               248
heart attack         125
traffic collision     56
lung cancer           51
pneumonia             50
Name: count, dtype: int64

In [41]:
# replace NaN with unknown
df["causeofdeath"] = df["causeofdeath"].fillna("unknown")
df["causeofdeath"].value_counts().head(5)

causeofdeath
unknown               5008
 cancer                248
 heart attack          125
 traffic collision      56
 lung cancer            51
Name: count, dtype: int64