# Exercise 14 - Selective updating

In this exercise, I want you to create the same two-column data frame as in the last exercise. Then, update the values in the ```temperature``` column so that any value less than 0 is set to 0.

In [17]:
import numpy as np
import pandas as pd

temperature = pd.read_csv('./nyc-temps.txt', dtype=np.float32).squeeze()
temp_df = pd.DataFrame(
  {
      "hour": [0, 3, 6, 9, 12, 15, 18, 21] * 91,
      "temperature": temperature
  })

temp_df.head(8)

   hour  temperature
0     0         -1.0
1     3         -1.0
2     6         -1.0
3     9         -1.0
4    12         -1.0
5    15         -1.0
6    18         -1.0
7    21          1.0

* Update the values in the ```temperature``` column so that any value less than 0 is set to 0.

In [18]:
temp_df_copy = temp_df.copy()
temp_df_copy.loc[temp_df_copy["temperature"] < 0, "temperature"]  = 0

temp_df_copy.head(8)

   hour  temperature
0     0          0.0
1     3          0.0
2     6          0.0
3     9          0.0
4    12          0.0
5    15          0.0
6    18          0.0
7    21          1.0

## Beyond the exercise

* Set all the odd temperatures to the mean of all the temperatures.

In [19]:
temp_df_copy = temp_df.copy()

In [20]:
temp_df_copy.loc[
    temp_df_copy["temperature"] % 2 == 1, # select odd temperatures
    "temperature"
] = temp_df_copy["temperature"].mean()

temp_df_copy.head(16)

    hour  temperature
0      0    -1.050824
1      3    -1.050824
2      6    -1.050824
3      9    -1.050824
4     12    -1.050824
5     15    -1.050824
6     18    -1.050824
7     21    -1.050824
8      0    -1.050824
9      3    -1.050824
10     6    -1.050824
11     9    -1.050824
12    12    -1.050824
13    15    -1.050824
14    18    -1.050824
15    21    -1.050824

*  Set the even temperatures at hours 9 and 18 to 3.

In [29]:
temp_df_copy = temp_df.copy()

In [30]:
temp_df_copy.loc[
    (temp_df_copy["temperature"] % 2 == 0) & (temp_df_copy["hour"].isin([9, 18])), # even temperatures at hours 9 and 18
    "temperature"
] = 3

temp_df_copy.head(16)

    hour  temperature
0      0         -1.0
1      3         -1.0
2      6         -1.0
3      9         -1.0
4     12         -1.0
5     15         -1.0
6     18         -1.0
7     21          1.0
8      0          1.0
9      3          1.0
10     6          1.0
11     9          1.0
12    12          1.0
13    15          1.0
14    18          1.0
15    21          1.0

* If the hour is odd, set the temperature to 5.

In [31]:
temp_df_copy = temp_df.copy()

In [32]:
temp_df_copy.loc[temp_df_copy["hour"] % 2 == 1, "temperature"] = 5

temp_df_copy.head(16)

    hour  temperature
0      0         -1.0
1      3          5.0
2      6         -1.0
3      9          5.0
4     12         -1.0
5     15          5.0
6     18         -1.0
7     21          5.0
8      0          1.0
9      3          5.0
10     6          1.0
11     9          5.0
12    12          1.0
13    15          5.0
14    18          1.0
15    21          5.0