# Exercise 10 - Adding new products

Good news! Your store is making money, and you have decided to add some new products. I’d like you to do that by creating a new data frame and adding it to the existing one. This new data frame should contain three products (including product ID, name, wholesale price, and retail price):

* Phone, with an ID of 24, a wholesale price of 200, and a retail price of 500
* Desktop, with an ID of 16, a wholesale price of 1000, and a retail price of 1600
* Headphones, with an ID of 17, a wholesale price of 75, and a retail price of 110

Because these are new products, don’t include the ```sales``` column. And to avoid problems and conflicts, ensure that the indexes of these new products are different from existing product indexes. (In chapter 4, we’ll look at some ways to handle index problems more elegantly.)

Once you have added these new products, assign sales figures to each of them. Finally, recalculate the store’s total net income, including the new products.

1. Recreate inventory from exercise 9

In [28]:
import pandas as pd
from pandas import DataFrame

pd.options.display.float_format = "{:,.2f}".format # use commas for thousands separator, and 2 decimal places

inventory = DataFrame(
    [
      [11, "keyboard", 10.00, 15.00, 20],
      [55, "Mouse", 5.00, 10.00, 32],
      [30, "Bluetooth Speaker", 20.00, 35.00, 50],
      [25, "Tablet", 200.00, 450.00, 10],
      [13, "Laptop", 500.00, 800.00, 36],
     ],
    columns=["product_id", "product_name", "wholesale_price", "retail_price", "sales"],
)

print(inventory)

   product_id       product_name  wholesale_price  retail_price  sales
0          11           keyboard            10.00         15.00     20
1          55              Mouse             5.00         10.00     32
2          30  Bluetooth Speaker            20.00         35.00     50
3          25             Tablet           200.00        450.00     10
4          13             Laptop           500.00        800.00     36

2. Add new products to inventory

In [29]:
new_products = DataFrame(
    [
        [24, "Phone", 200.00, 500.00],
        [16, "Desktop", 1000.00, 1700.00],
        [17, "Headphones", 75.00, 110.00]
    ],
    columns=["product_id", "product_name", "wholesale_price", "retail_price"],
    index=range(5, 8) # avoid collisions with the index of inventory DataFrame
)

inventory = pd.concat([inventory, new_products])

inventory

   product_id       product_name  wholesale_price  retail_price  sales
0          11           keyboard            10.00         15.00  20.00
1          55              Mouse             5.00         10.00  32.00
2          30  Bluetooth Speaker            20.00         35.00  50.00
3          25             Tablet           200.00        450.00  10.00
4          13             Laptop           500.00        800.00  36.00
5          24              Phone           200.00        500.00    NaN
6          16            Desktop         1,000.00      1,700.00    NaN
7          17         Headphones            75.00        110.00    NaN

3. Fill in sales info for the new products

In [30]:
inventory.loc[[5, 6, 7], "sales"] = [10, 20, 50]

inventory

   product_id       product_name  wholesale_price  retail_price  sales
0          11           keyboard            10.00         15.00  20.00
1          55              Mouse             5.00         10.00  32.00
2          30  Bluetooth Speaker            20.00         35.00  50.00
3          25             Tablet           200.00        450.00  10.00
4          13             Laptop           500.00        800.00  36.00
5          24              Phone           200.00        500.00  10.00
6          16            Desktop         1,000.00      1,700.00  20.00
7          17         Headphones            75.00        110.00  50.00

4. Calculate revenue of each product

In [31]:
inventory["revenue"] = (inventory["retail_price"] - inventory["wholesale_price"]) * inventory["sales"]


print(f"inventory:\n{inventory}\n\nTotal revenue: ${inventory['revenue'].sum():,.2f}")

inventory:
   product_id       product_name  wholesale_price  retail_price  sales  \
0          11           keyboard            10.00         15.00  20.00
1          55              Mouse             5.00         10.00  32.00
2          30  Bluetooth Speaker            20.00         35.00  50.00
3          25             Tablet           200.00        450.00  10.00
4          13             Laptop           500.00        800.00  36.00
5          24              Phone           200.00        500.00  10.00
6          16            Desktop         1,000.00      1,700.00  20.00
7          17         Headphones            75.00        110.00  50.00

    revenue
0    100.00
1    160.00
2    750.00
3  2,500.00
4 10,800.00
5  3,000.00
6 14,000.00
7  1,750.00

Total revenue: $33,060.00

## Beyond the exercise

*  Add one new product to the data frame without using ```pd.concat```. What’s the advantage of ```pd.concat```, and when should you use it?

In [32]:
new_product = DataFrame(
    [
        [18, "Phone Charger", 20, 35, 35],
    ],
    columns=["product_id", "product_name", "wholesale_price", "retail_price", "sales"],
    index=[8, ]
)

inventory.loc[len(inventory)] = new_product.loc[8] # add new product to inventory DataFrame

In [33]:
  # calculate revenue of new product
inventory.loc[8, "revenue"] = (inventory.loc[8, "retail_price"] - inventory.loc[8, "wholesale_price"]) * inventory.loc[8, "sales"]

print(f"inventory:\n{inventory}\n\nTotal revenue: ${inventory['revenue'].sum():,.2f}")

inventory:
   product_id       product_name  wholesale_price  retail_price  sales  \
0          11           keyboard            10.00         15.00  20.00
1          55              Mouse             5.00         10.00  32.00
2          30  Bluetooth Speaker            20.00         35.00  50.00
3          25             Tablet           200.00        450.00  10.00
4          13             Laptop           500.00        800.00  36.00
5          24              Phone           200.00        500.00  10.00
6          16            Desktop         1,000.00      1,700.00  20.00
7          17         Headphones            75.00        110.00  50.00
8          18      Phone Charger            20.00         35.00  35.00

    revenue
0    100.00
1    160.00
2    750.00
3  2,500.00
4 10,800.00
5  3,000.00
6 14,000.00
7  1,750.00
8    525.00

Total revenue: $33,585.00

* Add a new column, ```department```, to the data frame. Place each product in a department. For example, in our data, we would have three departments: ```electronics``` , ```computers```, and ```mobile devices```. Calculate revenue on the data frame, and then show descriptive statistics for the revenue on ```computers``` products.

In [34]:
# add department column
inventory["department"] = ["computers", "computers", "electronics", "mobile devices", "computers", "mobile devices", "computers", "electronics", "mobile devices"]

# rearrange columns
inventory = inventory[["product_id", "product_name", "department", "wholesale_price", "retail_price", "sales", "revenue"]]

inventory

,product_id,product_name,department,wholesale_price,retail_price,sales,revenue
0,11,keyboard,computers,10.00,15.00,20.00,100.00
1,55,Mouse,computers,5.00,10.00,32.00,160.00
2,30,Bluetooth Speaker,electronics,20.00,35.00,50.00,750.00
3,25,Tablet,mobile devices,200.00,450.00,10.00,"2,500.00"
4,13,Laptop,computers,500.00,800.00,36.00,"10,800.00"
5,24,Phone,mobile devices,200.00,500.00,10.00,"3,000.00"
6,16,Desktop,computers,"1,000.00","1,700.00",20.00,"14,000.00"
7,17,Headphones,electronics,75.00,110.00,50.00,"1,750.00"
8,18,Phone Charger,mobile devices,20.00,35.00,35.00,525.00

In [35]:
print(f"Total revenue: ${inventory['revenue'].sum():,.2f}\nStatistics for revenue of computer products:\n"
      f"{inventory.loc[inventory['department'] == 'computers', 'revenue'].describe()}")

Total revenue: $33,585.00
Statistics for revenue of computer products:
count        4.00
mean     6,265.00
std      7,203.58
min        100.00
25%        145.00
50%      5,480.00
75%     11,600.00
max     14,000.00
Name: revenue, dtype: float64

* Use the ```query``` method to get the descriptive statistics for ```computers``` items.

In [40]:
computer_stats = inventory.query('department == "computers"')['revenue'].describe() # note the "" surrounding computers category
print(f"Statistics for revenue of computer products:\n{computer_stats}")

Statistics for revenue of computer products:
count        4.00
mean     6,265.00
std      7,203.58
min        100.00
25%        145.00
50%      5,480.00
75%     11,600.00
max     14,000.00
Name: revenue, dtype: float64