# Exercise 11 - Bestsellers

You’re going to use the online store for one final exercise. This time, I want you to find the IDs and names of products that have sold more than the average number of units.

In [6]:
import pandas as pd

pd.options.display.float_format = "{:,.2f}".format # use commas for thousands separator, and 2 decimal places

inventory = pd.DataFrame( # create inventory
    [
      [11, "keyboard", 10.00, 15.00, 20],
      [55, "Mouse", 5.00, 10.00, 32],
      [30, "Bluetooth Speaker", 20.00, 35.00, 50],
      [25, "Tablet", 200.00, 450.00, 10],
      [13, "Laptop", 500.00, 800.00, 36],
      [24, "Phone", 200.00, 500.00, 10],
      [16, "Desktop", 1000.00, 1700.00, 20],
      [17, "Headphones", 75.00, 110.00, 50]
     ],
    columns=["product_id", "product_name", "wholesale_price", "retail_price", "sales"],
)

inventory

   product_id       product_name  wholesale_price  retail_price  sales
0          11           keyboard            10.00         15.00     20
1          55              Mouse             5.00         10.00     32
2          30  Bluetooth Speaker            20.00         35.00     50
3          25             Tablet           200.00        450.00     10
4          13             Laptop           500.00        800.00     36
5          24              Phone           200.00        500.00     10
6          16            Desktop         1,000.00      1,700.00     20
7          17         Headphones            75.00        110.00     50

In [7]:
# find bestseller products
bestsellers = inventory[["product_id", 'product_name', "sales"]][inventory["sales"] > inventory["sales"].mean()]

bestsellers

   product_id       product_name  sales
1          55              Mouse     32
2          30  Bluetooth Speaker     50
4          13             Laptop     36
7          17         Headphones     50

## Beyond the exercise

Here are some additional exercises that go beyond the task here. In each case, practice using both ```loc``` and ```query```:

* Show the ID and name of products whose net income is in the top 25% quantile.

In [12]:
# calculate revenue
inventory["revenue"] = (inventory["retail_price"] - inventory["wholesale_price"]) * inventory["sales"]

inventory

,product_id,product_name,wholesale_price,retail_price,sales,revenue
0,11,keyboard,10.00,15.00,20,100.00
1,55,Mouse,5.00,10.00,32,160.00
2,30,Bluetooth Speaker,20.00,35.00,50,750.00
3,25,Tablet,200.00,450.00,10,"2,500.00"
4,13,Laptop,500.00,800.00,36,"10,800.00"
5,24,Phone,200.00,500.00,10,"3,000.00"
6,16,Desktop,"1,000.00","1,700.00",20,"14,000.00"
7,17,Headphones,75.00,110.00,50,"1,750.00"

In [11]:
# products below 25% revenue percentile
inventory.loc[inventory["revenue"] <= inventory["revenue"].quantile(0.25), ["product_id", "product_name", "revenue"]]

   product_id product_name  revenue
0          11     keyboard   100.00
1          55        Mouse   160.00

* Show the ID and name of products with lower-than-average sales numbers and whose wholesale price is greater than the average.

In [16]:
inventory.loc[
  (inventory["sales"] < inventory["sales"].mean()) & (inventory["wholesale_price"] > inventory["wholesale_price"].mean()),
  ["product_id", "product_name", "wholesale_price", "sales"]
]

   product_id product_name  wholesale_price  sales
6          16      Desktop         1,000.00     20

* Show the name and wholesale and retail prices of products with IDs between 10 and 30 and that sold fewer than 20 units.

In [15]:
inventory.query('(product_id > 10 & product_id < 30) & sales < 20')[["product_id", "product_name", "wholesale_price", "retail_price", "sales"]]

   product_id product_name  wholesale_price  retail_price  sales
3          25       Tablet           200.00        450.00     10
5          24        Phone           200.00        500.00     10