# Exercise 21 - Parking tickets

In this exercise, I’ll ask you to perform some queries on another data set from New York City: one that tracked all parking tickets during the year 2020—more than 12 million of them. You could, in theory, perform these queries without modifying the data frame’s index. However, I want you to get some practice setting and resetting the index. We’re going to do that a lot in this chapter, and you’ll likely do it a great deal as you work with pandas with real-life data sets.

With that in mind, I want you to do the following:
1. Create a data frame from the file ```nyc-parking-violations-2020.csv```. We are only interested in a handful of the columns:
* ```Date First Observed```
* ```Plate ID```
* ```Registration State```
* ```Issue Date``` (a string in MM/DD/YYYY format, always followed by ```12:00:00AM```)
* ```Vehicle Make```
* ```Street Name```
* ```Vehicle Color```

In [5]:
import pandas as pd


nyc_data = pd.read_csv(
    filepath_or_buffer='./nyc-parking-violations-2020.csv', # NOTE: make sure this file is in the current folder
    usecols=[
        "Date First Observed",
        "Plate ID",
        "Registration State",
        "Issue Date",
        "Vehicle Make",
        "Street Name",
        "Vehicle Color"
    ]
)

nyc_data.head(10)

,Plate ID,Registration State,Issue Date,Vehicle Make,Street Name,Date First Observed,Vehicle Color
0,J58JKX,NJ,05/08/1972 12:00:00 AM,HONDA,43 ST,0,BK
1,KRE6058,PA,08/29/1977 12:00:00 AM,ME/BE,UNION ST,0,BLK
2,444326R,NJ,10/03/1988 12:00:00 AM,LEXUS,CLERMONT AVENUE,0,BLACK
3,F728330,OH,01/03/1990 12:00:00 AM,CHEVR,DIVISION AVE,0,NaN
4,FMY9090,NY,02/14/1990 12:00:00 AM,JEEP,GRAND ST,0,GREY
5,KDG0693,PA,07/21/1990 12:00:00 AM,HYUN,B 99 ST,0,GY
6,79928MG,NY,09/19/1990 12:00:00 AM,INTER,W/S/O WASHINGTON ST,0,WH
7,JJJ8186,NY,10/14/1990 12:00:00 AM,BMW,BAINBRIDGE AVE,0,BLK
8,DKD6024,NC,07/25/1991 12:00:00 AM,FORD,94 ST,0,GREY
9,6542FR,99,01/01/2000 12:00:00 AM,CMCKU,E 54 ST,0,RED

2. Set the data frame’s index to the ```Issue Date``` column.

In [6]:
nyc_data = nyc_data.set_index("Issue Date")

nyc_data.head(10)

,Plate ID,Registration State,Vehicle Make,Street Name,Date First Observed,Vehicle Color
Issue Date,,,,,,
05/08/1972 12:00:00 AM,J58JKX,NJ,HONDA,43 ST,0,BK
08/29/1977 12:00:00 AM,KRE6058,PA,ME/BE,UNION ST,0,BLK
10/03/1988 12:00:00 AM,444326R,NJ,LEXUS,CLERMONT AVENUE,0,BLACK
01/03/1990 12:00:00 AM,F728330,OH,CHEVR,DIVISION AVE,0,NaN
02/14/1990 12:00:00 AM,FMY9090,NY,JEEP,GRAND ST,0,GREY
07/21/1990 12:00:00 AM,KDG0693,PA,HYUN,B 99 ST,0,GY
09/19/1990 12:00:00 AM,79928MG,NY,INTER,W/S/O WASHINGTON ST,0,WH
10/14/1990 12:00:00 AM,JJJ8186,NY,BMW,BAINBRIDGE AVE,0,BLK
07/25/1991 12:00:00 AM,DKD6024,NC,FORD,94 ST,0,GREY
01/01/2000 12:00:00 AM,6542FR,99,CMCKU,E 54 ST,0,RED

3. Determine what three makes were most frequently ticketed on January 2, 2020.

In [9]:
most_ticketed_makes = nyc_data.loc["01/02/2020 12:00:00 AM", "Vehicle Make"].value_counts().head(3)

most_ticketed_makes

Vehicle Make
TOYOT    3829
HONDA    3593
FORD     3164
Name: count, dtype: int64

4. Determine the five streets on which cars got the most tickets on June 1, 2020.

In [10]:
most_ticketed_streets = nyc_data.loc["06/01/2020 12:00:00 AM", "Street Name"].value_counts().head(5)

most_ticketed_streets

Street Name
WB CONDUIT BLVD @ LI    1068
SB WEST ST @ LEROY S     335
EB HORACE HARDING EX     273
EB QUEENS BLVD @ 82N     245
WB ATLANTIC AVE @ CL     229
Name: count, dtype: int64

5. Set the index to ```Vehicle Color```.

In [11]:
nyc_data = nyc_data.reset_index().set_index("Vehicle Color")

nyc_data.head(10)

,Issue Date,Plate ID,Registration State,Vehicle Make,Street Name,Date First Observed
Vehicle Color,,,,,,
BK,05/08/1972 12:00:00 AM,J58JKX,NJ,HONDA,43 ST,0
BLK,08/29/1977 12:00:00 AM,KRE6058,PA,ME/BE,UNION ST,0
BLACK,10/03/1988 12:00:00 AM,444326R,NJ,LEXUS,CLERMONT AVENUE,0
NaN,01/03/1990 12:00:00 AM,F728330,OH,CHEVR,DIVISION AVE,0
GREY,02/14/1990 12:00:00 AM,FMY9090,NY,JEEP,GRAND ST,0
GY,07/21/1990 12:00:00 AM,KDG0693,PA,HYUN,B 99 ST,0
WH,09/19/1990 12:00:00 AM,79928MG,NY,INTER,W/S/O WASHINGTON ST,0
BLK,10/14/1990 12:00:00 AM,JJJ8186,NY,BMW,BAINBRIDGE AVE,0
GREY,07/25/1991 12:00:00 AM,DKD6024,NC,FORD,94 ST,0
RED,01/01/2000 12:00:00 AM,6542FR,99,CMCKU,E 54 ST,0

6. Determine the most common make of vehicles that were either red or blue.

In [12]:
most_common_make_BLUE_RED = nyc_data.loc[["BLUE", "RED"], "Vehicle Make"].value_counts().head(1)

most_common_make_BLUE_RED

Vehicle Make
HONDA    39353
Name: count, dtype: int64

## Beyond the execise

* What three car makes were most often ticketed from January 2 through January 10?

In [ ]:
# we can use slicing, but only after sorting the index from lowest to highest

nyc_data = nyc_data.reset_index().set_index("Issue Date")
nyc_data = nyc_data.sort_index()

In [15]:
most_ticketed_makes_2 = nyc_data.loc["01/02/2020 12:00:00 AM":"01/10/2020 12:00:00 AM", "Vehicle Make"].value_counts().head(3)

most_ticketed_makes_2

Vehicle Make
FORD     38958
TOYOT    37096
HONDA    35962
Name: count, dtype: int64

* How many tickets did the second-most-ticketed car get in 2020? (And why am I not interested in the most-ticketed plate?) What state was that car from, and was it always ticketed in the same location?

In [16]:
most_ticketed_car_2020 = nyc_data.loc["01/01/2020 12:00:00 AM":"12/31/2020 12:00:00 AM", "Plate ID"].value_counts().head(2)

# BLANKPLATE doesnt count
most_ticketed_car_2020

Plate ID
BLANKPLATE    8881
2704819       1535
Name: count, dtype: int64

In [17]:
# what state was the car from?

nyc_data = nyc_data.reset_index().set_index("Plate ID")

state = nyc_data.loc["2704819", "Registration State"].head(1)

state

Plate ID
2704819    IN
Name: Registration State, dtype: str

In [19]:
# was it always ticketed in the same location?

locations = nyc_data.loc["2704819", "Street Name"].value_counts().head(5)

locations

Street Name
8th Ave     395
Penn Plz    230
7th Ave      92
9th Ave      63
Broadway     57
Name: count, dtype: int64