# Exercise 23 - Olympic games

In this exercise, we’re going to build a deep multi-index, allowing us to retrieve data from various levels and in several ways. Specifically, I want you to do the following:

1.  Read the data file (```olympic_athlete_events.csv```) into a data frame. We only care about some of the columns: ```Age```, ```Height```, ```Team```, ```Year```, ```Season```, ```City```, ```Sport```, ```Event```, and ```Medal```. The multi-index should be based on ```Year```, ```Season```, ```Sport```, and ```Event```.

In [44]:
import pandas as pd

olympic_data = pd.read_csv(
    filepath_or_buffer="./olympic_athlete_events.csv", # NOTE: make sure this file is in this folder
    header=0,
    usecols=["Age", "Height", "Team", "Year", "Season", "City", "Sport", "Event", "Medal"],
    index_col=["Year", "Season", "Sport", "Event"],
)

olympic_data.head(10)

                                                               Age  Height  \
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball         24.0   180.0
2012 Summer Judo          Judo Men's Extra-Lightweight        23.0   170.0
1920 Summer Football      Football Men's Football             24.0     NaN
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War         34.0     NaN
1988 Winter Speed Skating Speed Skating Women's 500 metres    21.0   185.0
                          Speed Skating Women's 1,000 metres  21.0   185.0
1992 Winter Speed Skating Speed Skating Women's 500 metres    25.0   185.0
                          Speed Skating Women's 1,000 metres  25.0   185.0
1994 Winter Speed Skating Speed Skating Women's 500 metres    27.0   185.0
                          Speed Skating Women's 1,000 metres  27.0   185.0

                                                                        Team  \
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball                  China
2012 Summer Judo          Judo Men's Extra-Lightweight                 China
1920 Summer Football      Football Men's Football                    Denmark
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War         Denmark/Sweden
1988 Winter Speed Skating Speed Skating Women's 500 metres       Netherlands
                          Speed Skating Women's 1,000 metres     Netherlands
1992 Winter Speed Skating Speed Skating Women's 500 metres       Netherlands
                          Speed Skating Women's 1,000 metres     Netherlands
1994 Winter Speed Skating Speed Skating Women's 500 metres       Netherlands
                          Speed Skating Women's 1,000 metres     Netherlands

                                                                     City  \
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball           Barcelona
2012 Summer Judo          Judo Men's Extra-Lightweight             London
1920 Summer Football      Football Men's Football               Antwerpen
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War               Paris
1988 Winter Speed Skating Speed Skating Women's 500 metres        Calgary
                          Speed Skating Women's 1,000 metres      Calgary
1992 Winter Speed Skating Speed Skating Women's 500 metres    Albertville
                          Speed Skating Women's 1,000 metres  Albertville
1994 Winter Speed Skating Speed Skating Women's 500 metres    Lillehammer
                          Speed Skating Women's 1,000 metres  Lillehammer

                                                             Medal
Year Season Sport         Event
1992 Summer Basketball    Basketball Men's Basketball          NaN
2012 Summer Judo          Judo Men's Extra-Lightweight         NaN
1920 Summer Football      Football Men's Football              NaN
1900 Summer Tug-Of-War    Tug-Of-War Men's Tug-Of-War         Gold
1988 Winter Speed Skating Speed Skating Women's 500 metres     NaN
                          Speed Skating Women's 1,000 metres   NaN
1992 Winter Speed Skating Speed Skating Women's 500 metres     NaN
                          Speed Skating Women's 1,000 metres   NaN
1994 Winter Speed Skating Speed Skating Women's 500 metres     NaN
                          Speed Skating Women's 1,000 metres   NaN

2. Answer these questions:

- What is the average age of winning athletes in summer games held between 1936 and 2000?

In [45]:
# let's sort the indexes
olympic_data = olympic_data.sort_index()

olympic_data.head(10)

                                                     Age  Height  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  24.0     NaN
                      Athletics Men's 1,500 metres   NaN     NaN
                      Athletics Men's 1,500 metres  22.0     NaN
                      Athletics Men's 1,500 metres  23.0   154.0
                      Athletics Men's 1,500 metres  21.0     NaN
                      Athletics Men's 1,500 metres   NaN     NaN
                      Athletics Men's 1,500 metres  21.0     NaN
                      Athletics Men's 1,500 metres  18.0     NaN
                      Athletics Men's 100 metres    21.0   183.0
                      Athletics Men's 100 metres    23.0   176.0

                                                             Team    City  \
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  United States  Athina
                      Athletics Men's 1,500 metres         Greece  Athina
                      Athletics Men's 1,500 metres      Australia  Athina
                      Athletics Men's 1,500 metres        Germany  Athina
                      Athletics Men's 1,500 metres         Greece  Athina
                      Athletics Men's 1,500 metres         Greece  Athina
                      Athletics Men's 1,500 metres         France  Athina
                      Athletics Men's 1,500 metres         Greece  Athina
                      Athletics Men's 100 metres    United States  Athina
                      Athletics Men's 100 metres    United States  Athina

                                                     Medal
Year Season Sport     Event
1896 Summer Athletics Athletics Men's 1,500 metres  Silver
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres    Gold
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 1,500 metres  Bronze
                      Athletics Men's 1,500 metres     NaN
                      Athletics Men's 100 metres      Gold
                      Athletics Men's 100 metres       NaN

In [46]:
avg_age_winners = olympic_data.loc[(slice(1936, 2000), "Summer"), ["Age", "Medal"]].query('Medal == "Gold"')["Age"].mean()

print(f"Average Age of winners in summers games 1936-2000: {avg_age_winners:.1f} years old")

Average Age of winners in summers games 1936-2000: 25.1 years old

- What team has won the most medals in all archery events?

In [47]:
team_most_medals = olympic_data.loc[
    (
        slice(None), # include all years
        slice(None), # include all seasons
        "Archery"
    ),
    ["Team", "Medal"]
].query('Medal == "Gold"')["Team"].value_counts().head(1)

team_most_medals

Team
South Korea    49
Name: count, dtype: int64

* Starting in 1980, what is the average height of the “Table Tennis Women’s Team” event?

In [48]:
avg_height = olympic_data.loc[
    (
        slice(1980, None), # 1980 onwards
        slice(None), # include all seasons
        "Table Tennis",
        "Table Tennis Women's Doubles"
    ),
    "Height"
].mean()

print(f"Average height of the Table Tennis Women's Doubles: {avg_height:.1f} cm")

Average height of the Table Tennis Women's Doubles: 165.0 cm

* Starting in 1980, what is the average height of both “Table Tennis Women’s Team” and “Table Tennis Men’s Team”?

In [49]:
avg_height = olympic_data.loc[
    (
        slice(1980, None), # 1980 onwards
        slice(None), # include all seasons
        "Table Tennis",
        ["Table Tennis Women's Doubles", "Table Tennis Men's Doubles"]
    ),
    "Height"
].mean()

print(f"Average height of the Table Tennis Women/Men Doubles: {avg_height:.1f} cm")

Average height of the Table Tennis Women/Men Doubles: 171.1 cm

* How tall was the tallest-ever tennis player in Olympic games from 1980 until 2016?

In [50]:
height_tallest_tennis_player = olympic_data.loc[
    (
        slice(1980, 2016), # from 1980 to 2016
        slice(None), # include all seasons
        "Tennis",
        "Tennis Men's Singles"
    ),
    "Height"
].max()

print(f"Height of tallest tennis player from 1980-2016: {height_tallest_tennis_player:.1f} cm")

Height of tallest tennis player from 1980-2016: 208.0 cm

## Beyond the exercise

*  Events occur in either summer or winter Olympic Games, but not both. As a result, the "```Season```" level in our multi-index is often unnecessary. Remove the "```Season```" level, and then find (again) the height of the tallest tennis player between 1980 and 2016.

In [51]:
# remove "Season" from multi-index (and from dataframe)
olympic_data = olympic_data.droplevel(level="Season")

olympic_data.head(10)

                                              Age  Height           Team  \
Year Sport     Event
1896 Athletics Athletics Men's 1,500 metres  24.0     NaN  United States
               Athletics Men's 1,500 metres   NaN     NaN         Greece
               Athletics Men's 1,500 metres  22.0     NaN      Australia
               Athletics Men's 1,500 metres  23.0   154.0        Germany
               Athletics Men's 1,500 metres  21.0     NaN         Greece
               Athletics Men's 1,500 metres   NaN     NaN         Greece
               Athletics Men's 1,500 metres  21.0     NaN         France
               Athletics Men's 1,500 metres  18.0     NaN         Greece
               Athletics Men's 100 metres    21.0   183.0  United States
               Athletics Men's 100 metres    23.0   176.0  United States

                                               City   Medal
Year Sport     Event
1896 Athletics Athletics Men's 1,500 metres  Athina  Silver
               Athletics Men's 1,500 metres  Athina     NaN
               Athletics Men's 1,500 metres  Athina    Gold
               Athletics Men's 1,500 metres  Athina     NaN
               Athletics Men's 1,500 metres  Athina     NaN
               Athletics Men's 1,500 metres  Athina     NaN
               Athletics Men's 1,500 metres  Athina  Bronze
               Athletics Men's 1,500 metres  Athina     NaN
               Athletics Men's 100 metres    Athina    Gold
               Athletics Men's 100 metres    Athina     NaN

In [52]:
# find answer using xs method
height_tallest_tennis_player = olympic_data.xs(
    key=(slice(1980, 2016), "Tennis Men's Singles"),
    level=["Year", "Event"]
)["Height"].max()

print(f"Height of tallest tennis player from 1980-2016: {height_tallest_tennis_player:.1f} cm")

Height of tallest tennis player from 1980-2016: 208.0 cm

* In which city were the most gold medals awarded from 1980 onward?

In [53]:
# using IndexSlice
from pandas import IndexSlice as idx
city_gold = olympic_data.loc[idx[
    1980:, # from 1980 onwards
    :, # include all sports
    :, # include all events
    ],
    ["City", "Medal"] # select this columns
].query("Medal == 'Gold'")["City"].value_counts().head(1) # select city with more gold medals

city_gold

City
Beijing    671
Name: count, dtype: int64

* How many gold medals were received by the United States since 1980? (Use the index to select the values.)

In [54]:
usa_golds = olympic_data.loc[
    idx[
        1980:, # from 1980 onwards
        :, # include all sports
        :, # include all events
    ],
    ["Team", "Medal"] # select this columns
].query("(Team == 'United States') & (Medal == 'Gold')").shape[0]

print(f"USA Gold medals since 1980: {usa_golds:,.0f}")

USA Gold medals since 1980: 1,257