# Exercise 24 - Olympic pivots

In this exercise, we examine the Olympic data one more time—but using pivot tables, so we can examine and compare more information at a time than we could before. Pivot tables are a popular way to summarize information in a larger, more complex
table. I want you to do the following:

1. Read in our Olympic data again.
* Only use these columns: ```Age```, ```Height```, ```Team```, ```Year```, ```Season```, ```Sport```, ```Medal```.
* Only include games from 1980 to the present.
* Only include data from these countries: Great Britain, France, United States, Switzerland, China, and India.

In [23]:
import pandas as pd

olympic_data = pd.read_csv(
    filepath_or_buffer="./olympic_athlete_events.csv",
    header=0,
    usecols=["Age", "Height", "Team", "Year", "Season", "Sport", "Medal"]
)

olympic_data.head(10)

   Age  Height            Team  Year  Season          Sport Medal
0 24.0   180.0           China  1992  Summer     Basketball   NaN
1 23.0   170.0           China  2012  Summer           Judo   NaN
2 24.0     NaN         Denmark  1920  Summer       Football   NaN
3 34.0     NaN  Denmark/Sweden  1900  Summer     Tug-Of-War  Gold
4 21.0   185.0     Netherlands  1988  Winter  Speed Skating   NaN
5 21.0   185.0     Netherlands  1988  Winter  Speed Skating   NaN
6 25.0   185.0     Netherlands  1992  Winter  Speed Skating   NaN
7 25.0   185.0     Netherlands  1992  Winter  Speed Skating   NaN
8 27.0   185.0     Netherlands  1994  Winter  Speed Skating   NaN
9 27.0   185.0     Netherlands  1994  Winter  Speed Skating   NaN

In [24]:
# select rows of the following countries: Great Britain, France, United States, Switzerland, China, and India
olympic_data = olympic_data.loc[
    olympic_data["Team"].isin([
        "Great Britain",
        "France",
        "United States",
        "Switzerland",
        "China",
        "India"
    ])
]

# remove rows which "Year" is before 1980
olympic_data = olympic_data.loc[olympic_data["Year"] >= 1980]

olympic_data.head(10)

    Age  Height           Team  Year  Season                 Sport Medal
0  24.0   180.0          China  1992  Summer            Basketball   NaN
1  23.0   170.0          China  2012  Summer                  Judo   NaN
10 31.0   188.0  United States  1992  Winter  Cross Country Skiing   NaN
11 31.0   188.0  United States  1992  Winter  Cross Country Skiing   NaN
12 31.0   188.0  United States  1992  Winter  Cross Country Skiing   NaN
13 31.0   188.0  United States  1992  Winter  Cross Country Skiing   NaN
14 33.0   188.0  United States  1994  Winter  Cross Country Skiing   NaN
15 33.0   188.0  United States  1994  Winter  Cross Country Skiing   NaN
16 33.0   188.0  United States  1994  Winter  Cross Country Skiing   NaN
17 33.0   188.0  United States  1994  Winter  Cross Country Skiing   NaN

2. Answer the following questions:
*  What was the average age of Olympic athletes? In which country do players appear to consistently be the youngest?

In [25]:
pd.options.display.float_format = '{:,.1f}'.format
olympic_data.pivot_table(index="Year", columns="Team", values="Age")

Team  China  France  Great Britain  India  Switzerland  United States
Year
1980   21.9    23.5           22.9   25.5         24.6           22.8
1984   22.1    24.4           24.4   24.9         23.6           24.4
1988   22.4    24.5           25.4   24.0         26.2           24.9
1992   22.0    25.1           25.6   24.2         25.4           25.5
1994   20.6    24.6           25.3    NaN         25.5           25.0
1996   22.0    25.3           26.7   24.6         27.1           26.3
1998   21.8    25.5           27.2   16.0         25.6           25.1
2000   22.5    26.0           26.4   25.4         27.4           26.6
2002   23.1    25.7           26.8   20.0         26.2           25.7
2004   23.0    26.1           26.3   24.7         27.3           26.4
2006   23.5    26.3           26.9   25.2         26.3           25.6
2008   23.9    26.3           25.2   25.4         27.3           26.2
2010   23.2    25.9           26.1   25.7         26.5           25.8
2012   23.9    26.6           25.9   25.6         27.2           26.5
2014   23.4    25.7           25.6   25.0         25.9           26.2
2016   23.9    27.1           26.7   26.1         25.9           26.2

**Answer:** from the pivot table above, it seems China has the youngest athletes.

* How tall were the tallest athletes in each sport in each year?

In [26]:
olympic_data.pivot_table(index="Sport", columns="Year", values="Height", aggfunc="max")

Year,1980,1984,1988,1992,1994,1996,1998,2000,2002,2004,2006,2008,2010,2012,2014,2016
Sport,,,,,,,,,,,,,,,,
Alpine Skiing,184.0,184.0,185.0,185.0,188.0,NaN,188.0,NaN,189.0,NaN,193.0,NaN,193.0,NaN,200.0,NaN
Archery,185.0,188.0,188.0,191.0,NaN,191.0,NaN,191.0,NaN,193.0,NaN,193.0,NaN,193.0,NaN,188.0
Athletics,197.0,203.0,203.0,200.0,NaN,198.0,NaN,197.0,NaN,203.0,NaN,203.0,NaN,208.0,NaN,203.0
Badminton,NaN,NaN,NaN,186.0,NaN,189.0,NaN,187.0,NaN,190.0,NaN,190.0,NaN,191.0,NaN,191.0
Baseball,NaN,NaN,NaN,198.0,NaN,195.0,NaN,206.0,NaN,NaN,NaN,198.0,NaN,NaN,NaN,NaN
Basketball,196.0,216.0,216.0,216.0,NaN,216.0,NaN,226.0,NaN,226.0,NaN,226.0,NaN,221.0,NaN,218.0
Beach Volleyball,NaN,NaN,NaN,NaN,NaN,193.0,NaN,195.0,NaN,192.0,NaN,202.0,NaN,202.0,NaN,188.0
Biathlon,190.0,190.0,188.0,192.0,192.0,NaN,192.0,NaN,192.0,NaN,193.0,NaN,193.0,NaN,193.0,NaN
Bobsleigh,NaN,184.0,NaN,NaN,NaN,NaN,198.0,NaN,190.0,NaN,193.0,NaN,191.0,NaN,189.0,NaN
Boxing,190.0,195.0,196.0,193.0,NaN,191.0,NaN,198.0,NaN,190.0,NaN,203.0,NaN,201.0,NaN,200.0
Canoeing,203.0,203.0,203.0,203.0,NaN,205.0,NaN,203.0,NaN,190.0,NaN,200.0,NaN,194.0,NaN,191.0
Cross Country Skiing,185.0,189.0,186.0,190.0,190.0,NaN,185.0,NaN,188.0,NaN,188.0,NaN,193.0,NaN,193.0,NaN
Curling,NaN,NaN,NaN,NaN,NaN,NaN,188.0,NaN,193.0,NaN,183.0,NaN,189.0,NaN,192.0,NaN
Cycling,190.0,190.0,195.0,192.0,NaN,189.0,NaN,192.0,NaN,192.0,NaN,196.0,NaN,198.0,NaN,196.0
Diving,176.0,175.0,178.0,183.0,NaN,183.0,NaN,183.0,NaN,182.0,NaN,185.0,NaN,178.0,NaN,188.0
Equestrianism,179.0,187.0,187.0,184.0,NaN,196.0,NaN,187.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,196.0
Fencing,193.0,208.0,208.0,193.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,197.0,NaN,197.0
Figure Skating,183.0,182.0,180.0,182.0,182.0,NaN,182.0,NaN,183.0,NaN,188.0,NaN,188.0,NaN,193.0,NaN
Football,NaN,188.0,190.0,193.0,NaN,191.0,NaN,193.0,NaN,180.0,NaN,193.0,NaN,195.0,NaN,188.0
Freestyle Skiing,NaN,NaN,NaN,190.0,186.0,NaN,193.0,NaN,193.0,NaN,183.0,NaN,193.0,NaN,188.0,NaN
Golf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0
Gymnastics,180.0,179.0,181.0,178.0,NaN,180.0,NaN,175.0,NaN,176.0,NaN,184.0,NaN,184.0,NaN,184.0
Handball,197.0,200.0,200.0,198.0,NaN,203.0,NaN,199.0,NaN,199.0,NaN,201.0,NaN,204.0,NaN,202.0
Hockey,179.0,190.0,189.0,193.0,NaN,196.0,NaN,196.0,NaN,196.0,NaN,189.0,NaN,189.0,NaN,193.0
Ice Hockey,193.0,193.0,195.0,194.0,195.0,NaN,195.0,NaN,190.0,NaN,195.0,NaN,196.0,NaN,198.0,NaN
Judo,196.0,204.0,204.0,196.0,NaN,205.0,NaN,202.0,NaN,202.0,NaN,203.0,NaN,203.0,NaN,203.0
Luge,188.0,188.0,183.0,188.0,188.0,NaN,188.0,NaN,185.0,NaN,188.0,NaN,188.0,NaN,188.0,NaN
Modern Pentathlon,185.0,188.0,190.0,190.0,NaN,185.0,NaN,186.0,NaN,191.0,NaN,188.0,NaN,188.0,NaN,194.0
Nordic Combined,193.0,183.0,193.0,183.0,180.0,NaN,181.0,NaN,183.0,NaN,183.0,NaN,190.0,NaN,190.0,NaN
Rhythmic Gymnastics,NaN,172.0,170.0,172.0,NaN,172.0,NaN,173.0,NaN,178.0,NaN,177.0,NaN,173.0,NaN,177.0
Rowing,198.0,205.0,205.0,205.0,NaN,205.0,NaN,204.0,NaN,207.0,NaN,207.0,NaN,206.0,NaN,207.0
Rugby Sevens,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,195.0
Sailing,186.0,198.0,198.0,195.0,NaN,203.0,NaN,201.0,NaN,198.0,NaN,194.0,NaN,195.0,NaN,197.0
Shooting,183.0,189.0,190.0,190.0,NaN,195.0,NaN,188.0,NaN,192.0,NaN,192.0,NaN,198.0,NaN,200.0
Short Track Speed Skating,NaN,NaN,NaN,182.0,183.0,NaN,183.0,NaN,188.0,NaN,186.0,NaN,186.0,NaN,189.0,NaN
Skeleton,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.0,NaN,185.0,NaN,185.0,NaN,190.0,NaN
Ski Jumping,185.0,180.0,185.0,190.0,185.0,NaN,185.0,NaN,185.0,NaN,190.0,NaN,190.0,NaN,190.0,NaN
Snowboarding,NaN,NaN,NaN,NaN,NaN,NaN,190.0,NaN,190.0,NaN,186.0,NaN,190.0,NaN,188.0,NaN
Softball,NaN,NaN,NaN,NaN,NaN,182.0,NaN,185.0,NaN,188.0,NaN,191.0,NaN,NaN,NaN,NaN
Speed Skating,185.0,190.0,193.0,193.0,186.0,NaN,186.0,NaN,193.0,NaN,188.0,NaN,203.0,NaN,193.0,NaN
Swimming,194.0,200.0,200.0,201.0,NaN,201.0,NaN,201.0,NaN,202.0,NaN,203.0,NaN,203.0,NaN,206.0
Synchronized Swimming,NaN,178.0,180.0,180.0,NaN,181.0,NaN,181.0,NaN,177.0,NaN,175.0,NaN,178.0,NaN,177.0
Table Tennis,NaN,NaN,185.0,193.0,NaN,193.0,NaN,188.0,NaN,193.0,NaN,192.0,NaN,188.0,NaN,186.0
Taekwondo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198.0,NaN,198.0,NaN,201.0,NaN,201.0,NaN,197.0
Tennis,NaN,NaN,193.0,200.0,NaN,200.0,NaN,198.0,NaN,188.0,NaN,198.0,NaN,206.0,NaN,196.0
Trampolining,NaN,NaN,NaN,NaN,NaN,NaN,NaN,175.0,NaN,172.0,NaN,179.0,NaN,179.0,NaN,178.0
Triathlon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192.0,NaN,191.0,NaN,196.0,NaN,191.0,NaN,191.0
Volleyball,NaN,203.0,203.0,202.0,NaN,203.0,NaN,204.0,NaN,209.0,NaN,210.0,NaN,206.0,NaN,209.0
Water Polo,NaN,198.0,205.0,205.0,NaN,200.0,NaN,200.0,NaN,203.0,NaN,201.0,NaN,203.0,NaN,206.0
Weightlifting,180.0,188.0,190.0,190.0,NaN,195.0,NaN,182.0,NaN,180.0,NaN,177.0,NaN,189.0,NaN,187.0
Wrestling,205.0,190.0,193.0,193.0,NaN,194.0,NaN,196.0,NaN,195.0,NaN,203.0,NaN,203.0,NaN,188.0

* How many medals did each country earn each year?

In [27]:
# olympic_data = olympic_data.dropna(subset="Medal")

olympic_data.pivot_table(
    index="Year",
    columns="Team",
    values="Medal",
    aggfunc="count"
)

Team  China  France  Great Britain  India  Switzerland  United States
Year
1980    0.0    30.0           48.0   16.0          5.0           30.0
1984   74.0    70.0           71.0    0.0         17.0          359.0
1988   50.0    31.0           54.0    0.0         24.0          212.0
1992   73.0    65.0           50.0    0.0          2.0          236.0
1994    3.0    11.0            3.0    NaN          8.0           19.0
1996   94.0    49.0           26.0    1.0         11.0          255.0
1998   14.0    13.0            4.0    0.0         10.0           30.0
2000   65.0    64.0           52.0    1.0         14.0          240.0
2002   14.0    13.0            6.0    0.0         20.0           70.0
2004   82.0    53.0           55.0    1.0          5.0          259.0
2006    9.0    15.0            1.0    0.0         15.0           48.0
2008  170.0    77.0           81.0    3.0         11.0          309.0
2010   15.0    14.0            1.0    0.0         12.0           89.0
2012  117.0    78.0          122.0    6.0          4.0          238.0
2014   12.0    18.0           10.0    0.0         28.0           52.0
2016  109.0    96.0          145.0    2.0         11.0          256.0

## Beyond the exercise

* Create a pivot table that shows the number of medals each team won per year, with the index including the year and the season in which the games took place.

In [28]:
olympic_data.pivot_table(index=["Year", "Season"], columns="Team", values="Medal", aggfunc="count")

Team         China  France  Great Britain  India  Switzerland  United States
Year Season
1980 Summer    NaN    29.0           47.0   16.0          2.0            NaN
     Winter    0.0     1.0            1.0    NaN          3.0           30.0
1984 Summer   74.0    67.0           71.0    0.0         13.0          352.0
     Winter    0.0     3.0            0.0    NaN          4.0            7.0
1988 Summer   50.0    29.0           54.0    0.0          8.0          207.0
     Winter    0.0     2.0            0.0    0.0         16.0            5.0
1992 Summer   70.0    55.0           50.0    0.0          1.0          222.0
     Winter    3.0    10.0            0.0    0.0          1.0           14.0
1994 Winter    3.0    11.0            3.0    NaN          8.0           19.0
1996 Summer   94.0    49.0           26.0    1.0         11.0          255.0
1998 Winter   14.0    13.0            4.0    0.0         10.0           30.0
2000 Summer   65.0    64.0           52.0    1.0         14.0          240.0
2002 Winter   14.0    13.0            6.0    0.0         20.0           70.0
2004 Summer   82.0    53.0           55.0    1.0          5.0          259.0
2006 Winter    9.0    15.0            1.0    0.0         15.0           48.0
2008 Summer  170.0    77.0           81.0    3.0         11.0          309.0
2010 Winter   15.0    14.0            1.0    0.0         12.0           89.0
2012 Summer  117.0    78.0          122.0    6.0          4.0          238.0
2014 Winter   12.0    18.0           10.0    0.0         28.0           52.0
2016 Summer  109.0    96.0          145.0    2.0         11.0          256.0

* Create a pivot table that shows both the average age and the average height per year per team.

In [29]:
olympic_data.pivot_table(index="Year", columns="Team", values=["Age", "Height"])

       Age                                                      Height         \
Team China France Great Britain India Switzerland United States  China France
Year
1980  21.9   23.5          22.9  25.5        24.6          22.8  162.6  175.1
1984  22.1   24.4          24.4  24.9        23.6          24.4  171.6  176.3
1988  22.4   24.5          25.4  24.0        26.2          24.9  171.3  176.2
1992  22.0   25.1          25.6  24.2        25.4          25.5  171.0  175.2
1994  20.6   24.6          25.3   NaN        25.5          25.0  169.2  173.0
1996  22.0   25.3          26.7  24.6        27.1          26.3  170.4  174.5
1998  21.8   25.5          27.2  16.0        25.6          25.1  168.9  174.8
2000  22.5   26.0          26.4  25.4        27.4          26.6  171.0  176.2
2002  23.1   25.7          26.8  20.0        26.2          25.7  169.0  175.8
2004  23.0   26.1          26.3  24.7        27.3          26.4  172.7  176.1
2006  23.5   26.3          26.9  25.2        26.3          25.6  170.3  174.0
2008  23.9   26.3          25.2  25.4        27.3          26.2  176.0  177.0
2010  23.2   25.9          26.1  25.7        26.5          25.8  169.6  174.8
2012  23.9   26.6          25.9  25.6        27.2          26.5  175.5  177.3
2014  23.4   25.7          25.6  25.0        25.9          26.2  169.8  173.8
2016  23.9   27.1          26.7  26.1        25.9          26.2  175.0  177.7


Team Great Britain India Switzerland United States
Year
1980         175.4 170.8       177.0         175.0
1984         174.4 169.4       173.4         176.9
1988         176.1 168.7       176.6         176.6
1992         176.1 172.5       175.3         176.4
1994         172.9   NaN       174.1         175.4
1996         177.4 171.8       174.1         177.5
1998         173.8 183.0       174.3         173.5
2000         176.5 173.3       176.5         177.3
2002         173.1 183.0       176.2         173.8
2004         176.7 169.9       176.3         176.9
2006         176.1 167.8       176.0         173.9
2008         176.9 173.1       176.1         177.5
2010         176.3 176.0       176.6         174.5
2012         177.8 173.6       177.1         178.1
2014         173.4 170.0       174.0         174.7
2016         176.4 170.0       173.9         177.8

* Create a pivot table that shows the average age and the average height per year, per team, broken up by year and season.

In [30]:
olympic_data.pivot_table(
    index=["Year", "Season"],
    columns="Team",
    values=["Age", "Height"]
)

              Age                                                      Height  \
Team        China France Great Britain India Switzerland United States  China
Year Season
1980 Summer   NaN   23.7          22.8  25.5        25.3           NaN    NaN
     Winter  21.9   22.8          23.6   NaN        23.5          22.8  162.6
1984 Summer  22.1   24.3          24.5  24.9        23.7          24.6  172.1
     Winter  22.0   24.8          24.4   NaN        23.4          23.6  166.3
1988 Summer  22.5   24.5          25.8  24.1        27.6          25.2  171.3
     Winter  19.6   24.6          23.4  22.7        24.4          23.6  175.0
1992 Summer  22.0   25.6          25.9  24.4        26.3          25.6  170.9
     Winter  21.9   24.0          23.8  20.5        24.1          24.9  171.8
1994 Winter  20.6   24.6          25.3   NaN        25.5          25.0  169.2
1996 Summer  22.0   25.3          26.7  24.6        27.1          26.3  170.4
1998 Winter  21.8   25.5          27.2  16.0        25.6          25.1  168.9
2000 Summer  22.5   26.0          26.4  25.4        27.4          26.6  171.0
2002 Winter  23.1   25.7          26.8  20.0        26.2          25.7  169.0
2004 Summer  23.0   26.1          26.3  24.7        27.3          26.4  172.7
2006 Winter  23.5   26.3          26.9  25.2        26.3          25.6  170.3
2008 Summer  23.9   26.3          25.2  25.4        27.3          26.2  176.0
2010 Winter  23.2   25.9          26.1  25.7        26.5          25.8  169.6
2012 Summer  23.9   26.6          25.9  25.6        27.2          26.5  175.5
2014 Winter  23.4   25.7          25.6  25.0        25.9          26.2  169.8
2016 Summer  23.9   27.1          26.7  26.1        25.9          26.2  175.0


Team        France Great Britain India Switzerland United States
Year Season
1980 Summer  175.9         175.5 170.8       180.5           NaN
     Winter  171.4         174.5   NaN       171.6         175.0
1984 Summer  176.5         174.4 169.4       173.9         177.2
     Winter  174.6         174.1   NaN       171.4         175.2
1988 Summer  176.2         176.6 168.7       176.8         177.1
     Winter  176.1         172.8   NaN       176.3         174.5
1992 Summer  176.0         176.6 172.5       175.6         176.9
     Winter  173.0         173.3   NaN       175.0         174.5
1994 Winter  173.0         172.9   NaN       174.1         175.4
1996 Summer  174.5         177.4 171.8       174.1         177.5
1998 Winter  174.8         173.8 183.0       174.3         173.5
2000 Summer  176.2         176.5 173.3       176.5         177.3
2002 Winter  175.8         173.1 183.0       176.2         173.8
2004 Summer  176.1         176.7 169.9       176.3         176.9
2006 Winter  174.0         176.1 167.8       176.0         173.9
2008 Summer  177.0         176.9 173.1       176.1         177.5
2010 Winter  174.8         176.3 176.0       176.6         174.5
2012 Summer  177.3         177.8 173.6       177.1         178.1
2014 Winter  173.8         173.4 170.0       174.0         174.7
2016 Summer  177.7         176.4 170.0       173.9         177.8