# Exercise 22 - State SAT scores

In this exercise, we look at a summary of scores from the SAT, a standardized university admissions test widely used in the United States. The CSV file (```sat-scores.csv```) has 99 columns and 577 rows describing all 50 US states and three nonstates (Puerto Rico, the Virgin Islands, and Washington, DC) from 2005 through 2015. In this exercise, I want you to:

1. Read in the scores file, only keeping the ```Year```, ```State.Code```, ```Total.Math```, ```Total.Test-takers```, and ```Total.Verbal``` columns.

In [1]:
from heapq import heappush

import pandas as pd

test_scores = pd.read_csv(
    filepath_or_buffer="./sat-scores.csv",
    header=0,
    usecols=["Year", "State.Code", "Total.Math", "Total.Test-takers", "Total.Verbal"]
)

test_scores.head(10)

   Year State.Code  Total.Math  Total.Test-takers  Total.Verbal
0  2005         AL         559               3985           567
1  2005         AK         519               3996           523
2  2005         AZ         530              18184           526
3  2005         AR         552               1600           563
4  2005         CA         522             186552           504
5  2005         CO         560              11990           560
6  2005         CT         517              34313           517
7  2005         DE         502               6257           503
8  2005         DC         478               3622           490
9  2005         FL         498              93505           498

2. Create a multi-index based on the year and the two-letter state code.

In [2]:
test_scores = test_scores.set_index(["Year", "State.Code"])

test_scores.head(10)

                 Total.Math  Total.Test-takers  Total.Verbal
Year State.Code
2005 AL                 559               3985           567
     AK                 519               3996           523
     AZ                 530              18184           526
     AR                 552               1600           563
     CA                 522             186552           504
     CO                 560              11990           560
     CT                 517              34313           517
     DE                 502               6257           503
     DC                 478               3622           490
     FL                 498              93505           498

3. Determine how many people took the SAT in 2005.

In [4]:
n_test_takers_2005 = test_scores.loc[2005, "Total.Test-takers"].sum()

print(f"Test takers in 2005: {n_test_takers_2005:,.0f}")

Test takers in 2005: 1,344,824

4.  Determine the average SAT math score in 2010 from New York (NY), New Jersey (NJ), Massachusetts (MA), and Illinois (IL).

In [6]:
avg_test_scores = test_scores.loc[([2010, ], ["NY", "NJ", "MA", "IL"]), "Total.Math"].mean()

print(f"Average math score in 2010 from NY, NJ, MA, IL: {avg_test_scores:,.2f}")

Average math score in 2010 for NY, NJ, MA, IL: 535.25

5. Determine the average SAT verbal score in 2012–2015 from Arizona (AZ), California ( CA), and Texas (TX).

In [20]:
avg_test_scores = test_scores.loc[(slice(2012,2015), ["AZ", "CA", "TX"]), "Total.Verbal"].mean()

print(f"Average verbal score in 2012-2015 from AZ, CA, TX: {avg_test_scores:,.2f}")

Average verbal score in 2012-2015 from AZ, CA, TX: 497.33

## Beyond the exercise

*  What were the average math and verbal scores for Florida, Indiana, and Idaho across all years? (Don’t break out the values by state.)

In [12]:
avg_test_scores = test_scores.loc[(slice(None), ["FL", "IN", "ID"]), ["Total.Math", "Total.Verbal"]].mean()

avg_test_scores

Total.Math      507.090909
Total.Verbal    504.606061
dtype: float64

* Which state received the highest verbal score, and in which year?

In [16]:
index = test_scores["Total.Verbal"].idxmax()

print(f"The state with the highest verbal score is: {index[1]}\n"
      f"Obtained in the year {index[0]}\n"
      f"with a score of {test_scores.loc[index, 'Total.Verbal']:,.2f}"
      )

The state with the highest verbal score is: ND
Obtained in the year 2013
with a score of 612.00

* Was the average math score in 2005 higher or lower than that in 2015?

In [18]:
math_score_2005 = test_scores.loc[2005, "Total.Math"].mean()
math_score_2015 = test_scores.loc[2015, "Total.Math"].mean()

print(f"Math score in 2005: {math_score_2005:,.2f}\n"
      f"Math score in 2015: {math_score_2015:,.2f}\n"
      f"The year with the higher math score is: {2015 if math_score_2015 > math_score_2005 else 2005}\n"
      )

Math score in 2005: 535.65
Math score in 2015: 533.09
The year with the higher math score is: 2005